var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/custom-variants/route.js")
R.c("server/chunks/[root-of-the-server]__c14fed53._.js")
R.c("server/chunks/node_modules_next_92aaecbe._.js")
R.c("server/chunks/_3577e4f1._.js")
R.c("server/chunks/node_modules_next_3188e0b6._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/[root-of-the-server]__7ad58425._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_custom-variants_route_actions_e24daaac.js")
R.m(11580)
module.exports=R.m(11580).exports
