var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/calculadora/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__60c3cd32._.js")
R.c("server/chunks/ssr/node_modules_next_dist_cc88faaa._.js")
R.c("server/chunks/ssr/_96487aa5._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1b5ca5d0._.js")
R.c("server/chunks/ssr/node_modules_e8f67c40._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_0cc614fa._.js")
R.c("server/chunks/ssr/node_modules_next_dist_174ae28d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__f9176f67._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_calculadora_page_actions_4374ca9c.js")
R.m(59865)
module.exports=R.m(59865).exports
