var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/super-admin/update-store-plan/route.js")
R.c("server/chunks/[root-of-the-server]__19acfa55._.js")
R.c("server/chunks/node_modules_next_92aaecbe._.js")
R.c("server/chunks/_3577e4f1._.js")
R.c("server/chunks/[root-of-the-server]__7ad58425._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/node_modules_next_0700e68e._.js")
R.c("server/chunks/ce889_server_app_api_super-admin_update-store-plan_route_actions_3fad4697.js")
R.m(917)
module.exports=R.m(917).exports
