var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/shipping/enviamelo/points/route.js")
R.c("server/chunks/[root-of-the-server]__e5954e83._.js")
R.c("server/chunks/node_modules_next_92aaecbe._.js")
R.c("server/chunks/_3577e4f1._.js")
R.c("server/chunks/[root-of-the-server]__7ad58425._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/node_modules_next_0700e68e._.js")
R.c("server/chunks/_next-internal_server_app_api_shipping_enviamelo_points_route_actions_2da07230.js")
R.m(81529)
module.exports=R.m(81529).exports
