var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/feed/google/[subdomain]/route.js")
R.c("server/chunks/[root-of-the-server]__01ef535e._.js")
R.c("server/chunks/node_modules_next_92aaecbe._.js")
R.c("server/chunks/_3577e4f1._.js")
R.c("server/chunks/node_modules_next_3188e0b6._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/[root-of-the-server]__7ad58425._.js")
R.c("server/chunks/_next-internal_server_app_api_feed_google_[subdomain]_route_actions_8792e63b.js")
R.m(66397)
module.exports=R.m(66397).exports
