module.exports = [
"[externals]/next/dist/shared/lib/no-fallback-error.external.js [external] (next/dist/shared/lib/no-fallback-error.external.js, cjs)", ((__turbopack_context__, module, exports) => {

const mod = __turbopack_context__.x("next/dist/shared/lib/no-fallback-error.external.js", () => require("next/dist/shared/lib/no-fallback-error.external.js"));

module.exports = mod;
}),
"[project]/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/app/layout.tsx [app-rsc] (ecmascript)"));
}),
"[project]/app/plan-gratis/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/app/plan-gratis/layout.tsx [app-rsc] (ecmascript)"));
}),
"[project]/app/plan-gratis/page-client.tsx [app-rsc] (client reference proxy) <module evaluation>", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "default",
    ()=>__TURBOPACK__default__export__
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const __TURBOPACK__default__export__ = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call the default export of [project]/app/plan-gratis/page-client.tsx <module evaluation> from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/app/plan-gratis/page-client.tsx <module evaluation>", "default");
}),
"[project]/app/plan-gratis/page-client.tsx [app-rsc] (client reference proxy)", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "default",
    ()=>__TURBOPACK__default__export__
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const __TURBOPACK__default__export__ = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call the default export of [project]/app/plan-gratis/page-client.tsx from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/app/plan-gratis/page-client.tsx", "default");
}),
"[project]/app/plan-gratis/page-client.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

var __TURBOPACK__imported__module__$5b$project$5d2f$app$2f$plan$2d$gratis$2f$page$2d$client$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__$3c$module__evaluation$3e$__ = __turbopack_context__.i("[project]/app/plan-gratis/page-client.tsx [app-rsc] (client reference proxy) <module evaluation>");
var __TURBOPACK__imported__module__$5b$project$5d2f$app$2f$plan$2d$gratis$2f$page$2d$client$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__ = __turbopack_context__.i("[project]/app/plan-gratis/page-client.tsx [app-rsc] (client reference proxy)");
;
__turbopack_context__.n(__TURBOPACK__imported__module__$5b$project$5d2f$app$2f$plan$2d$gratis$2f$page$2d$client$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__);
}),
"[project]/components/seo-extra-block.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "SeoExtraBlock",
    ()=>SeoExtraBlock
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f40$supabase$2f$supabase$2d$js$2f$dist$2f$index$2e$mjs__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$locals$3e$__ = __turbopack_context__.i("[project]/node_modules/@supabase/supabase-js/dist/index.mjs [app-rsc] (ecmascript) <locals>");
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$cache$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/cache.js [app-rsc] (ecmascript)");
;
;
;
async function getSeoExtra(page) {
    (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$cache$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["unstable_noStore"])();
    try {
        const supabase = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f40$supabase$2f$supabase$2d$js$2f$dist$2f$index$2e$mjs__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$locals$3e$__["createClient"])(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY);
        const { data } = await supabase.from("page_content").select("value").eq("page", page).eq("key", "seo_extra").single();
        return data?.value || null;
    } catch  {
        return null;
    }
}
async function SeoExtraBlock({ page }) {
    const content = await getSeoExtra(page);
    if (!content) return null;
    const paragraphs = content.split("\n\n").filter(Boolean);
    return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("section", {
        className: "bg-slate-50 border-t border-slate-100 py-12",
        children: /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
            className: "container mx-auto px-4 max-w-4xl",
            children: /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                className: "prose prose-slate max-w-none text-slate-600 text-sm leading-relaxed space-y-4",
                children: paragraphs.map((p, i)=>{
                    if (p.startsWith("## ")) {
                        return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("h2", {
                            className: "text-lg font-semibold text-slate-800 mt-6 mb-2",
                            children: p.replace("## ", "")
                        }, i, false, {
                            fileName: "[project]/components/seo-extra-block.tsx",
                            lineNumber: 39,
                            columnNumber: 22
                        }, this);
                    }
                    if (p.startsWith("### ")) {
                        return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("h3", {
                            className: "text-base font-semibold text-slate-700 mt-4 mb-2",
                            children: p.replace("### ", "")
                        }, i, false, {
                            fileName: "[project]/components/seo-extra-block.tsx",
                            lineNumber: 42,
                            columnNumber: 22
                        }, this);
                    }
                    return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("p", {
                        children: p
                    }, i, false, {
                        fileName: "[project]/components/seo-extra-block.tsx",
                        lineNumber: 44,
                        columnNumber: 20
                    }, this);
                })
            }, void 0, false, {
                fileName: "[project]/components/seo-extra-block.tsx",
                lineNumber: 36,
                columnNumber: 9
            }, this)
        }, void 0, false, {
            fileName: "[project]/components/seo-extra-block.tsx",
            lineNumber: 35,
            columnNumber: 7
        }, this)
    }, void 0, false, {
        fileName: "[project]/components/seo-extra-block.tsx",
        lineNumber: 34,
        columnNumber: 5
    }, this);
}
}),
"[project]/app/plan-gratis/page.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>Page
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$app$2f$plan$2d$gratis$2f$page$2d$client$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/app/plan-gratis/page-client.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$components$2f$seo$2d$extra$2d$block$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/components/seo-extra-block.tsx [app-rsc] (ecmascript)");
;
;
;
// Schema.org: WebPage + FAQ + Offer para plan gratuito permanente
const jsonLd = {
    "@context": "https://schema.org",
    "@graph": [
        {
            "@type": "WebPage",
            "@id": "https://tol.ar/plan-gratis",
            url: "https://tol.ar/plan-gratis",
            name: "Plan gratuito para tienda online en Argentina — tol.ar",
            description: "Creá tu tienda online gratis en Argentina para siempre. Sin tarjeta de crédito, sin comisiones por venta, sin fecha de vencimiento. El único plan realmente gratis de Argentina.",
            inLanguage: "es-AR",
            isPartOf: {
                "@id": "https://tol.ar/#website"
            },
            breadcrumb: {
                "@type": "BreadcrumbList",
                itemListElement: [
                    {
                        "@type": "ListItem",
                        position: 1,
                        name: "Inicio",
                        item: "https://tol.ar"
                    },
                    {
                        "@type": "ListItem",
                        position: 2,
                        name: "Plan Gratis",
                        item: "https://tol.ar/plan-gratis"
                    }
                ]
            }
        },
        {
            "@type": "FAQPage",
            mainEntity: [
                {
                    "@type": "Question",
                    name: "¿El plan gratis de tol.ar vence?",
                    acceptedAnswer: {
                        "@type": "Answer",
                        text: "No. El plan gratuito de tol.ar es permanente, no vence nunca. No es un período de prueba de 14 días como en otras plataformas. Podés tener tu tienda online gratis para siempre en Argentina."
                    }
                },
                {
                    "@type": "Question",
                    name: "¿Qué incluye el plan gratis de tol.ar?",
                    acceptedAnswer: {
                        "@type": "Answer",
                        text: "El plan gratuito de tol.ar incluye: tienda online con dominio propio (tutienda.tol.ar), productos ilimitados con fotos y variantes, carrito de compras, MercadoPago integrado para cobrar con tarjeta o transferencia, métodos de envío (Correo Argentino, retiro en local), emails automáticos de confirmación de pedido, y panel de administración completo. Todo gratis, sin tarjeta de crédito."
                    }
                },
                {
                    "@type": "Question",
                    name: "¿tol.ar cobra comisión por venta en el plan gratis?",
                    acceptedAnswer: {
                        "@type": "Answer",
                        text: "No. tol.ar no cobra comisión por venta en el plan gratuito. Otras plataformas cobran un porcentaje adicional sobre cada venta cuando usás MercadoPago; en tol.ar vendés y te quedás con el 100% de tus ventas (menos la comisión estándar de MercadoPago que cobra MercadoPago directamente, no tol.ar)."
                    }
                },
                {
                    "@type": "Question",
                    name: "¿Puedo crear una tienda online gratis en Argentina sin saber programación?",
                    acceptedAnswer: {
                        "@type": "Answer",
                        text: "Sí. tol.ar está diseñado para emprendedores sin conocimientos técnicos. En menos de 2 minutos podés tener tu tienda online funcionando: elegís el rubro, cargás tus productos y empezás a vender. No necesitás saber programar ni diseñar."
                    }
                },
                {
                    "@type": "Question",
                    name: "¿El plan gratuito de tol.ar es realmente permanente?",
                    acceptedAnswer: {
                        "@type": "Answer",
                        text: "Sí. tol.ar tiene plan gratuito permanente sin comisiones: no vence, no es un período de prueba, no se convierte en pago. Podés mantener tu tienda activa indefinidamente sin pagar nada. Solo pagás si elegís agregar funciones opcionales."
                    }
                },
                {
                    "@type": "Question",
                    name: "¿Necesito tarjeta de crédito para crear una tienda gratis en tol.ar?",
                    acceptedAnswer: {
                        "@type": "Answer",
                        text: "No. Para crear tu tienda online gratis en tol.ar solo necesitás un email. No pedimos tarjeta de crédito, no hay ningún cargo oculto. Es completamente gratis para empezar."
                    }
                },
                {
                    "@type": "Question",
                    name: "¿Cuántas tiendas online se pueden crear gratis en tol.ar?",
                    acceptedAnswer: {
                        "@type": "Answer",
                        text: "Podés crear 1 tienda online gratis con el plan gratuito de tol.ar. Si necesitás más tiendas, podés contratar planes adicionales. Actualmente hay más de 383 tiendas activas creadas con tol.ar en Argentina."
                    }
                }
            ]
        },
        {
            "@type": "Product",
            "@id": "https://tol.ar/#plan-gratis",
            name: "Plan Gratis tol.ar — Tienda Online",
            description: "Plan gratuito permanente para crear tienda online en Argentina. Sin comisiones, sin tarjeta de crédito, sin fecha de vencimiento. Incluye MercadoPago, productos ilimitados y panel de administración.",
            brand: {
                "@type": "Brand",
                name: "tol.ar"
            },
            offers: {
                "@type": "Offer",
                price: "0",
                priceCurrency: "ARS",
                availability: "https://schema.org/InStock",
                url: "https://tol.ar/plan-gratis",
                description: "Plan gratuito permanente para tienda online en Argentina",
                seller: {
                    "@type": "Organization",
                    "@id": "https://tol.ar/#organization"
                }
            }
        }
    ]
};
function Page() {
    return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["Fragment"], {
        children: [
            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("script", {
                type: "application/ld+json",
                dangerouslySetInnerHTML: {
                    __html: JSON.stringify(jsonLd)
                }
            }, void 0, false, {
                fileName: "[project]/app/plan-gratis/page.tsx",
                lineNumber: 115,
                columnNumber: 7
            }, this),
            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$app$2f$plan$2d$gratis$2f$page$2d$client$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["default"], {}, void 0, false, {
                fileName: "[project]/app/plan-gratis/page.tsx",
                lineNumber: 119,
                columnNumber: 7
            }, this),
            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$components$2f$seo$2d$extra$2d$block$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["SeoExtraBlock"], {
                page: "plan-gratis"
            }, void 0, false, {
                fileName: "[project]/app/plan-gratis/page.tsx",
                lineNumber: 120,
                columnNumber: 7
            }, this)
        ]
    }, void 0, true);
}
}),
"[project]/app/plan-gratis/page.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/app/plan-gratis/page.tsx [app-rsc] (ecmascript)"));
}),
];

//# sourceMappingURL=%5Broot-of-the-server%5D__98fa5523._.js.map