module.exports = [
"[project]/components/store/cart-provider.tsx [app-rsc] (client reference proxy) <module evaluation>", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "CartProvider",
    ()=>CartProvider,
    "useCart",
    ()=>useCart
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const CartProvider = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call CartProvider() from the server but CartProvider is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/components/store/cart-provider.tsx <module evaluation>", "CartProvider");
const useCart = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call useCart() from the server but useCart is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/components/store/cart-provider.tsx <module evaluation>", "useCart");
}),
"[project]/components/store/cart-provider.tsx [app-rsc] (client reference proxy)", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "CartProvider",
    ()=>CartProvider,
    "useCart",
    ()=>useCart
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const CartProvider = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call CartProvider() from the server but CartProvider is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/components/store/cart-provider.tsx", "CartProvider");
const useCart = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call useCart() from the server but useCart is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/components/store/cart-provider.tsx", "useCart");
}),
"[project]/components/store/cart-provider.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

var __TURBOPACK__imported__module__$5b$project$5d2f$components$2f$store$2f$cart$2d$provider$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__$3c$module__evaluation$3e$__ = __turbopack_context__.i("[project]/components/store/cart-provider.tsx [app-rsc] (client reference proxy) <module evaluation>");
var __TURBOPACK__imported__module__$5b$project$5d2f$components$2f$store$2f$cart$2d$provider$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__ = __turbopack_context__.i("[project]/components/store/cart-provider.tsx [app-rsc] (client reference proxy)");
;
__turbopack_context__.n(__TURBOPACK__imported__module__$5b$project$5d2f$components$2f$store$2f$cart$2d$provider$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__);
}),
"[project]/components/store/tracking-pixels.tsx [app-rsc] (client reference proxy) <module evaluation>", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "TrackingPixels",
    ()=>TrackingPixels,
    "trackEvent",
    ()=>trackEvent
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const TrackingPixels = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call TrackingPixels() from the server but TrackingPixels is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/components/store/tracking-pixels.tsx <module evaluation>", "TrackingPixels");
const trackEvent = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call trackEvent() from the server but trackEvent is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/components/store/tracking-pixels.tsx <module evaluation>", "trackEvent");
}),
"[project]/components/store/tracking-pixels.tsx [app-rsc] (client reference proxy)", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "TrackingPixels",
    ()=>TrackingPixels,
    "trackEvent",
    ()=>trackEvent
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const TrackingPixels = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call TrackingPixels() from the server but TrackingPixels is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/components/store/tracking-pixels.tsx", "TrackingPixels");
const trackEvent = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call trackEvent() from the server but trackEvent is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/components/store/tracking-pixels.tsx", "trackEvent");
}),
"[project]/components/store/tracking-pixels.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

var __TURBOPACK__imported__module__$5b$project$5d2f$components$2f$store$2f$tracking$2d$pixels$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__$3c$module__evaluation$3e$__ = __turbopack_context__.i("[project]/components/store/tracking-pixels.tsx [app-rsc] (client reference proxy) <module evaluation>");
var __TURBOPACK__imported__module__$5b$project$5d2f$components$2f$store$2f$tracking$2d$pixels$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__ = __turbopack_context__.i("[project]/components/store/tracking-pixels.tsx [app-rsc] (client reference proxy)");
;
__turbopack_context__.n(__TURBOPACK__imported__module__$5b$project$5d2f$components$2f$store$2f$tracking$2d$pixels$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__);
}),
"[project]/components/store/whatsapp-button.tsx [app-rsc] (client reference proxy) <module evaluation>", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "WhatsAppButton",
    ()=>WhatsAppButton
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const WhatsAppButton = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call WhatsAppButton() from the server but WhatsAppButton is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/components/store/whatsapp-button.tsx <module evaluation>", "WhatsAppButton");
}),
"[project]/components/store/whatsapp-button.tsx [app-rsc] (client reference proxy)", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "WhatsAppButton",
    ()=>WhatsAppButton
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const WhatsAppButton = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call WhatsAppButton() from the server but WhatsAppButton is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/components/store/whatsapp-button.tsx", "WhatsAppButton");
}),
"[project]/components/store/whatsapp-button.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

var __TURBOPACK__imported__module__$5b$project$5d2f$components$2f$store$2f$whatsapp$2d$button$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__$3c$module__evaluation$3e$__ = __turbopack_context__.i("[project]/components/store/whatsapp-button.tsx [app-rsc] (client reference proxy) <module evaluation>");
var __TURBOPACK__imported__module__$5b$project$5d2f$components$2f$store$2f$whatsapp$2d$button$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__ = __turbopack_context__.i("[project]/components/store/whatsapp-button.tsx [app-rsc] (client reference proxy)");
;
__turbopack_context__.n(__TURBOPACK__imported__module__$5b$project$5d2f$components$2f$store$2f$whatsapp$2d$button$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__);
}),
"[project]/lib/supabase/server.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "createClient",
    ()=>createClient,
    "createServerClient",
    ()=>createServerClient,
    "createServerSupabaseClient",
    ()=>createServerSupabaseClient
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f40$supabase$2f$ssr$2f$dist$2f$module$2f$index$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$locals$3e$__ = __turbopack_context__.i("[project]/node_modules/@supabase/ssr/dist/module/index.js [app-rsc] (ecmascript) <locals>");
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f40$supabase$2f$ssr$2f$dist$2f$module$2f$createServerClient$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/@supabase/ssr/dist/module/createServerClient.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$headers$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/headers.js [app-rsc] (ecmascript)");
;
;
async function createServerClient() {
    const cookieStore = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$headers$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["cookies"])();
    return (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f40$supabase$2f$ssr$2f$dist$2f$module$2f$createServerClient$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["createServerClient"])(("TURBOPACK compile-time value", "https://tuznlaqncbrsbokbbzhy.supabase.co"), ("TURBOPACK compile-time value", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1em5sYXFuY2Jyc2Jva2Jiemh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQwMjc4NDIsImV4cCI6MjA4OTYwMzg0Mn0.bWF8DNO6_HISbJnEIA9qufKN9qwMAyIZM2cjhWUrkQI"), {
        cookies: {
            getAll () {
                return cookieStore.getAll();
            },
            setAll (cookiesToSet) {
                try {
                    cookiesToSet.forEach(({ name, value, options })=>cookieStore.set(name, value, options));
                } catch  {
                // Server Component - can be ignored
                }
            }
        }
    });
}
const createClient = createServerClient;
const createServerSupabaseClient = createServerClient;
}),
"[project]/lib/services/stores.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

// ===========================================
// SERVICIO DE TIENDAS - tol.ar
// ===========================================
__turbopack_context__.s([
    "getAllStores",
    ()=>getAllStores,
    "getStoreById",
    ()=>getStoreById,
    "getStoreBySubdomain",
    ()=>getStoreBySubdomain,
    "getStoreFeatures",
    ()=>getStoreFeatures,
    "getStorePurchasedFeatures",
    ()=>getStorePurchasedFeatures,
    "hasStoreFeature",
    ()=>hasStoreFeature,
    "updateLastLogin",
    ()=>updateLastLogin
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$supabase$2f$server$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/lib/supabase/server.ts [app-rsc] (ecmascript)");
;
async function getStoreBySubdomain(subdomain) {
    try {
        const supabase = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$supabase$2f$server$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["createClient"])();
        const { data, error } = await supabase.from("stores").select("*").eq("subdomain", subdomain.toLowerCase()).eq("status", "active").single();
        if (error || !data) return null;
        return data;
    } catch (e) {
        console.error("[stores] Error in getStoreBySubdomain:", e);
        return null;
    }
}
async function getStoreById(storeId) {
    try {
        const supabase = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$supabase$2f$server$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["createClient"])();
        const { data, error } = await supabase.from("stores").select("*").eq("id", storeId).single();
        if (error || !data) return null;
        return data;
    } catch (e) {
        console.error("[stores] Error in getStoreById:", e);
        return null;
    }
}
async function getAllStores() {
    try {
        const supabase = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$supabase$2f$server$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["createClient"])();
        const { data, error } = await supabase.from("stores").select("*").order("created_at", {
            ascending: false
        });
        if (error || !data) return [];
        return data;
    } catch (e) {
        console.error("[stores] Error in getAllStores:", e);
        return [];
    }
}
async function updateLastLogin(storeId) {
    try {
        const supabase = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$supabase$2f$server$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["createClient"])();
        await supabase.from("stores").update({
            last_login: new Date().toISOString()
        }).eq("id", storeId);
    } catch (e) {
        console.error("[stores] Error in updateLastLogin:", e);
    }
}
async function getStoreFeatures(storeId) {
    try {
        const supabase = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$supabase$2f$server$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["createClient"])();
        const { data, error } = await supabase.from("store_purchased_features").select("feature_code").eq("store_id", storeId).eq("is_active", true);
        if (error || !data) return [];
        return data.map((f)=>f.feature_code);
    } catch (e) {
        console.error("[stores] Error in getStoreFeatures:", e);
        return [];
    }
}
async function hasStoreFeature(storeId, featureCode) {
    const features = await getStoreFeatures(storeId);
    return features.includes(featureCode);
}
async function getStorePurchasedFeatures(storeId) {
    try {
        const supabase = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$supabase$2f$server$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["createClient"])();
        const { data, error } = await supabase.from("store_purchased_features").select("feature_code").eq("store_id", storeId).eq("is_active", true);
        if (error || !data) return [];
        return data.map((f)=>f.feature_code);
    } catch (e) {
        console.error("[stores] Error in getStorePurchasedFeatures:", e);
        return [];
    }
}
}),
"[project]/lib/services/products.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

// ===========================================
// SERVICIO DE PRODUCTOS - tol.ar
// ===========================================
__turbopack_context__.s([
    "generateSlug",
    ()=>generateSlug,
    "getFeaturedProducts",
    ()=>getFeaturedProducts,
    "getProductBySlug",
    ()=>getProductBySlug,
    "getProductsByCategory",
    ()=>getProductsByCategory,
    "getStoreCategories",
    ()=>getStoreCategories,
    "getStoreProducts",
    ()=>getStoreProducts
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$supabase$2f$server$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/lib/supabase/server.ts [app-rsc] (ecmascript)");
;
async function getStoreProducts(storeId) {
    try {
        const supabase = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$supabase$2f$server$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["createClient"])();
        const { data, error } = await supabase.from("products").select("*").eq("store_id", storeId).eq("active", true).order("display_order", {
            ascending: true,
            nullsFirst: false
        }).order("created_at", {
            ascending: false
        });
        if (error || !data) return [];
        return data;
    } catch (e) {
        console.error("[products] Error in getStoreProducts:", e);
        return [];
    }
}
async function getFeaturedProducts(storeId, limit = 8) {
    try {
        const supabase = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$supabase$2f$server$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["createClient"])();
        const { data, error } = await supabase.from("products").select("*").eq("store_id", storeId).eq("active", true).eq("featured", true).limit(limit);
        if (error || !data) return [];
        return data;
    } catch (e) {
        console.error("[products] Error in getFeaturedProducts:", e);
        return [];
    }
}
async function getProductBySlug(storeId, slug) {
    try {
        const supabase = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$supabase$2f$server$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["createClient"])();
        // Primero intentar buscar por slug exacto
        const { data } = await supabase.from("products").select("*").eq("store_id", storeId).eq("slug", slug).eq("active", true).maybeSingle();
        if (data) return data;
        // Si no encuentra por slug, intentar buscar por ID (por si el slug es un UUID)
        if (slug.match(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i)) {
            const { data: dataById } = await supabase.from("products").select("*").eq("store_id", storeId).eq("id", slug).eq("active", true).single();
            if (dataById) return dataById;
        }
        // Si hay múltiples productos con el mismo slug, tomar el primero
        const { data: dataMultiple } = await supabase.from("products").select("*").eq("store_id", storeId).ilike("slug", slug).eq("active", true).limit(1).single();
        if (dataMultiple) return dataMultiple;
        return null;
    } catch (e) {
        console.error("[products] Error in getProductBySlug:", e);
        return null;
    }
}
async function getProductsByCategory(storeId, categoryId) {
    try {
        const supabase = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$supabase$2f$server$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["createClient"])();
        const { data, error } = await supabase.from("products").select("*").eq("store_id", storeId).eq("category_id", categoryId).eq("active", true).order("display_order", {
            ascending: true,
            nullsFirst: false
        }).order("created_at", {
            ascending: false
        });
        if (error || !data) return [];
        return data;
    } catch (e) {
        console.error("[products] Error in getProductsByCategory:", e);
        return [];
    }
}
async function getStoreCategories(storeId) {
    try {
        const supabase = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$supabase$2f$server$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["createClient"])();
        const { data, error } = await supabase.from("categories").select("*").eq("store_id", storeId).order("name", {
            ascending: true
        });
        if (error || !data) return [];
        return data;
    } catch (e) {
        console.error("[products] Error in getStoreCategories:", e);
        return [];
    }
}
function generateSlug(name) {
    return name.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}
}),
"[project]/lib/services/orders.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

// ===========================================
// SERVICIO DE PEDIDOS - tol.ar
// ===========================================
__turbopack_context__.s([
    "getOrderById",
    ()=>getOrderById,
    "getOrderStats",
    ()=>getOrderStats,
    "getStoreOrders",
    ()=>getStoreOrders,
    "updateOrderPayment",
    ()=>updateOrderPayment,
    "updateOrderStatus",
    ()=>updateOrderStatus
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$supabase$2f$server$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/lib/supabase/server.ts [app-rsc] (ecmascript)");
;
async function getStoreOrders(storeId) {
    try {
        const supabase = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$supabase$2f$server$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["createClient"])();
        const { data, error } = await supabase.from("orders").select("*").eq("store_id", storeId).order("created_at", {
            ascending: false
        });
        if (error || !data) return [];
        return data;
    } catch (e) {
        console.error("[orders] Error in getStoreOrders:", e);
        return [];
    }
}
async function getOrderById(orderId) {
    try {
        const supabase = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$supabase$2f$server$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["createClient"])();
        const { data, error } = await supabase.from("orders").select("*").eq("id", orderId).single();
        if (error || !data) return null;
        return data;
    } catch (e) {
        console.error("[orders] Error in getOrderById:", e);
        return null;
    }
}
async function updateOrderStatus(orderId, status) {
    try {
        const supabase = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$supabase$2f$server$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["createClient"])();
        const { error } = await supabase.from("orders").update({
            status
        }).eq("id", orderId);
        return !error;
    } catch (e) {
        console.error("[orders] Error in updateOrderStatus:", e);
        return false;
    }
}
async function updateOrderPayment(orderId, paymentId, status = "pagado") {
    try {
        const supabase = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$supabase$2f$server$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["createClient"])();
        const { error } = await supabase.from("orders").update({
            status,
            payment_id: paymentId
        }).eq("id", orderId);
        return !error;
    } catch (e) {
        console.error("[orders] Error in updateOrderPayment:", e);
        return false;
    }
}
async function getOrderStats(storeId) {
    try {
        const supabase = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$supabase$2f$server$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["createClient"])();
        const { data, error } = await supabase.from("orders").select("total, status, created_at").eq("store_id", storeId);
        if (error || !data) return null;
        const totalOrders = data.length;
        const totalRevenue = data.filter((o)=>o.status === "pagado" || o.status === "entregado").reduce((sum, o)=>sum + (o.total || 0), 0);
        const pendingOrders = data.filter((o)=>o.status === "pendiente").length;
        const paidOrders = data.filter((o)=>o.status === "pagado" || o.status === "entregado").length;
        return {
            totalOrders,
            totalRevenue,
            pendingOrders,
            paidOrders
        };
    } catch (e) {
        console.error("[orders] Error in getOrderStats:", e);
        return null;
    }
}
}),
"[project]/lib/services/payments.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

// ===========================================
// SERVICIO DE PAGOS - tol.ar
// ===========================================
__turbopack_context__.s([
    "createMPPreference",
    ()=>createMPPreference,
    "getMercadoPagoToken",
    ()=>getMercadoPagoToken,
    "getPaymentMethods",
    ()=>getPaymentMethods,
    "validateMPToken",
    ()=>validateMPToken
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$supabase$2f$server$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/lib/supabase/server.ts [app-rsc] (ecmascript)");
;
async function getPaymentMethods(storeId) {
    try {
        const supabase = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$supabase$2f$server$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["createClient"])();
        const { data, error } = await supabase.from("payment_methods").select("*").eq("store_id", storeId).single();
        if (error || !data) return null;
        return data;
    } catch (e) {
        console.error("[payments] Error in getPaymentMethods:", e);
        return null;
    }
}
async function getMercadoPagoToken(storeId) {
    try {
        const supabase = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$supabase$2f$server$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["createClient"])();
        const { data, error } = await supabase.from("payment_methods").select("mercadopago_access_token, mercadopago_test_mode, mercadopago_test_token, mercadopago_checkout_type").eq("store_id", storeId).single();
        if (error || !data) return null;
        const isTestMode = data.mercadopago_test_mode || false;
        const token = isTestMode ? data.mercadopago_test_token : data.mercadopago_access_token;
        if (!token) return null;
        return {
            token,
            isTestMode,
            checkoutType: decrypted.mercadopago_checkout_type || "redirect"
        };
    } catch (e) {
        console.error("[payments] Error in getMercadoPagoToken:", e);
        return null;
    }
}
function validateMPToken(token) {
    if (token.startsWith("APP_USR-")) {
        return {
            valid: true,
            type: "production"
        };
    }
    if (token.startsWith("TEST-")) {
        return {
            valid: true,
            type: "test"
        };
    }
    return {
        valid: false,
        type: "invalid"
    };
}
async function createMPPreference(accessToken, orderId, items, customerEmail, backUrls) {
    const preferenceData = {
        items: items.map((item)=>({
                title: item.name,
                quantity: item.quantity,
                unit_price: item.price,
                currency_id: "ARS"
            })),
        payer: {
            email: customerEmail
        },
        back_urls: backUrls,
        auto_return: "approved",
        external_reference: orderId,
        notification_url: `${("TURBOPACK compile-time value", "https://tol.ar") || "https://tol.ar"}/api/mercadopago/webhook`
    };
    const response = await fetch("https://api.mercadopago.com/checkout/preferences", {
        method: "POST",
        headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${accessToken}`
        },
        body: JSON.stringify(preferenceData)
    });
    if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.message || "Error al crear preferencia de pago");
    }
    return response.json();
}
}),
"[project]/lib/services/index.ts [app-rsc] (ecmascript) <locals>", ((__turbopack_context__) => {
"use strict";

// ===========================================
// SERVICIOS - tol.ar
// ===========================================
// Exportación centralizada de todos los servicios
// Tiendas
__turbopack_context__.s([]);
var __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$services$2f$stores$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/lib/services/stores.ts [app-rsc] (ecmascript)");
// Productos
var __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$services$2f$products$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/lib/services/products.ts [app-rsc] (ecmascript)");
// Pedidos
var __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$services$2f$orders$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/lib/services/orders.ts [app-rsc] (ecmascript)");
// Pagos
var __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$services$2f$payments$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/lib/services/payments.ts [app-rsc] (ecmascript)");
;
;
;
;
}),
"[project]/lib/store-context.ts [app-rsc] (ecmascript) <locals>", ((__turbopack_context__) => {
"use strict";

// ===========================================
// STORE CONTEXT - tol.ar
// ===========================================
// Este archivo re-exporta los servicios para mantener
// compatibilidad con los imports existentes.
// Para nuevos desarrollos, usar directamente:
// import { ... } from "@/lib/services"
// ===========================================
// Re-exportar tipos
__turbopack_context__.s([]);
// Re-exportar servicios
var __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$services$2f$index$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$locals$3e$__ = __turbopack_context__.i("[project]/lib/services/index.ts [app-rsc] (ecmascript) <locals>");
var __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$services$2f$stores$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/lib/services/stores.ts [app-rsc] (ecmascript)");
;
;
}),
"[project]/components/store/lupa-tracker.tsx [app-rsc] (client reference proxy) <module evaluation>", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "LupaTracker",
    ()=>LupaTracker
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const LupaTracker = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call LupaTracker() from the server but LupaTracker is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/components/store/lupa-tracker.tsx <module evaluation>", "LupaTracker");
}),
"[project]/components/store/lupa-tracker.tsx [app-rsc] (client reference proxy)", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "LupaTracker",
    ()=>LupaTracker
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const LupaTracker = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call LupaTracker() from the server but LupaTracker is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/components/store/lupa-tracker.tsx", "LupaTracker");
}),
"[project]/components/store/lupa-tracker.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

var __TURBOPACK__imported__module__$5b$project$5d2f$components$2f$store$2f$lupa$2d$tracker$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__$3c$module__evaluation$3e$__ = __turbopack_context__.i("[project]/components/store/lupa-tracker.tsx [app-rsc] (client reference proxy) <module evaluation>");
var __TURBOPACK__imported__module__$5b$project$5d2f$components$2f$store$2f$lupa$2d$tracker$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__ = __turbopack_context__.i("[project]/components/store/lupa-tracker.tsx [app-rsc] (client reference proxy)");
;
__turbopack_context__.n(__TURBOPACK__imported__module__$5b$project$5d2f$components$2f$store$2f$lupa$2d$tracker$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__);
}),
"[project]/app/tienda/[subdomain]/layout.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>StoreLayout
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$components$2f$store$2f$cart$2d$provider$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/components/store/cart-provider.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$components$2f$store$2f$page$2d$tracker$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/components/store/page-tracker.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$components$2f$store$2f$tracking$2d$pixels$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/components/store/tracking-pixels.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$components$2f$store$2f$whatsapp$2d$button$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/components/store/whatsapp-button.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$store$2d$context$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$locals$3e$__ = __turbopack_context__.i("[project]/lib/store-context.ts [app-rsc] (ecmascript) <locals>");
var __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$services$2f$stores$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/lib/services/stores.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$components$2f$store$2f$lupa$2d$tracker$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/components/store/lupa-tracker.tsx [app-rsc] (ecmascript)");
;
;
;
;
;
;
;
async function StoreLayout({ children, params }) {
    const { subdomain } = await params;
    const store = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$services$2f$stores$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getStoreBySubdomain"])(subdomain);
    // Obtener pixels y verificacion de dominio
    const pixels = store?.marketing_settings?.pixels || {};
    const verification = store?.marketing_settings?.verification || {};
    // Verificar si tiene la feature de WhatsApp
    const purchasedFeatures = store ? await (0, __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$services$2f$stores$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getStorePurchasedFeatures"])(store.id) : [];
    const hasWhatsAppFeature = purchasedFeatures.includes("whatsapp_chat");
    const hasLupaFeature = purchasedFeatures.includes("lupa");
    const whatsappNumber = store?.social_whatsapp || store?.whatsapp_number;
    return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$components$2f$store$2f$cart$2d$provider$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["CartProvider"], {
        children: [
            store && /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$components$2f$store$2f$page$2d$tracker$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["PageTracker"], {
                storeId: store.id
            }, void 0, false, {
                fileName: "[project]/app/tienda/[subdomain]/layout.tsx",
                lineNumber: 31,
                columnNumber: 17
            }, this),
            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$components$2f$store$2f$tracking$2d$pixels$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["TrackingPixels"], {
                metaPixelId: pixels.meta_pixel_id,
                tiktokPixelId: pixels.tiktok_pixel_id,
                googleAnalyticsId: pixels.google_analytics_id,
                domainVerificationMeta: verification.meta_domain,
                domainVerificationGoogle: verification.google_site
            }, void 0, false, {
                fileName: "[project]/app/tienda/[subdomain]/layout.tsx",
                lineNumber: 32,
                columnNumber: 7
            }, this),
            children,
            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$components$2f$store$2f$lupa$2d$tracker$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["LupaTracker"], {
                subdomain: subdomain,
                hasLupa: hasLupaFeature
            }, void 0, false, {
                fileName: "[project]/app/tienda/[subdomain]/layout.tsx",
                lineNumber: 40,
                columnNumber: 7
            }, this),
            hasWhatsAppFeature && whatsappNumber && /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$components$2f$store$2f$whatsapp$2d$button$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["WhatsAppButton"], {
                phoneNumber: whatsappNumber,
                storeName: store?.site_title
            }, void 0, false, {
                fileName: "[project]/app/tienda/[subdomain]/layout.tsx",
                lineNumber: 42,
                columnNumber: 9
            }, this)
        ]
    }, void 0, true, {
        fileName: "[project]/app/tienda/[subdomain]/layout.tsx",
        lineNumber: 30,
        columnNumber: 5
    }, this);
}
}),
];

//# sourceMappingURL=_d59a6766._.js.map