var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/orders/route.js")
R.c("server/chunks/node_modules_@react-email_render_dist_node_index_mjs_1bf9c5b5._.js")
R.c("server/chunks/node_modules_next_9ecaf93a._.js")
R.c("server/chunks/node_modules_@opentelemetry_api_build_esm_7e8f41ca._.js")
R.c("server/chunks/node_modules_@supabase_auth-js_dist_module_02e1b12e._.js")
R.c("server/chunks/node_modules_postal-mime_src_a014ae66._.js")
R.c("server/chunks/node_modules_svix_dist_56996d0e._.js")
R.c("server/chunks/node_modules_4281b5c0._.js")
R.c("server/chunks/[root-of-the-server]__dfb209ba._.js")
R.c("server/chunks/_next-internal_server_app_api_orders_route_actions_9a6edca0.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/orders/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/orders/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
