var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/blog/cuanto-cuesta-tienda-online-argentina/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0b3c0359._.js")
R.c("server/chunks/ssr/node_modules_next_dist_cc88faaa._.js")
R.c("server/chunks/ssr/_dbeef70a._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1b5ca5d0._.js")
R.c("server/chunks/ssr/node_modules_e8f67c40._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_0cc614fa._.js")
R.c("server/chunks/ssr/node_modules_next_dist_174ae28d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__f9176f67._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/app_blog_layout_tsx_ff46dc5c._.js")
R.c("server/chunks/ssr/node_modules_@supabase_supabase-js_dist_index_mjs_1b27b6a8._.js")
R.c("server/chunks/ssr/ce889_server_app_blog_cuanto-cuesta-tienda-online-argentina_page_actions_857aa78e.js")
R.m(99948)
module.exports=R.m(99948).exports
